// generate-report.mjs — Render the cross-vertical-comparison data
// as either Markdown (AEO/SEO-friendly) or JSON (machine-readable).

import { VERTICALS, SHAPES, MATRIX, CROSS_CUTTING_INVARIANTS } from "./cross-vertical-data.mjs";

export function renderJson() {
  return JSON.stringify({
    generated_purpose: "Cross-vertical comparison of the Kinetic Gain Protocol Suite's 6 vertical 6-packs. Surfaces SAME canonical shapes and DIFFERENT per-vertical design contributions across all 36 sibling spec repos.",
    verticals: VERTICALS,
    shapes: SHAPES,
    matrix: MATRIX,
    cross_cutting_invariants: CROSS_CUTTING_INVARIANTS
  }, null, 2);
}

export function renderMarkdown() {
  const lines = [];

  lines.push("# Kinetic Gain Protocol Suite — Cross-Vertical Comparison");
  lines.push("");
  lines.push("> Auto-generated reference table comparing the **6 vertical 6-packs** of the Kinetic Gain Protocol Suite: the SAME canonical shapes that appear in every vertical, and the DIFFERENT per-vertical design contributions that distinguish each one. 36 sibling spec repos × 6 verticals.");
  lines.push("");
  lines.push("Generated by [`kg-suite-vertical-comparator`](https://github.com/mizcausevic-dev/kg-suite-vertical-comparator).");
  lines.push("");

  // --- Section 1: The Six Verticals ---
  lines.push("## The Six Regulated Verticals");
  lines.push("");
  lines.push("| Vertical | Federal Floor | Canonical Buyer | Canonical Vendor |");
  lines.push("|---|---|---|---|");
  for (const v of VERTICALS) {
    lines.push(`| **${v.name}** | ${v.federal_floor} | ${v.canonical_buyer} | ${v.canonical_vendor} |`);
  }
  lines.push("");

  // --- Section 2: The Six Canonical Shapes ---
  lines.push("## The Six Canonical Shapes (per vertical)");
  lines.push("");
  lines.push("Every vertical 6-pack contains exactly these six artifact-shape repos:");
  lines.push("");
  lines.push("| Shape | Description |");
  lines.push("|---|---|");
  for (const s of SHAPES) {
    lines.push(`| **${s.name}** | ${s.description} |`);
  }
  lines.push("");

  // --- Section 3: The 6 × 6 Matrix ---
  lines.push("## The 6 × 6 Matrix");
  lines.push("");
  lines.push("Each cell names the actual repo + its key design innovation vs the sibling-vertical equivalent.");
  lines.push("");
  for (const s of SHAPES) {
    lines.push(`### ${s.name}`);
    lines.push("");
    lines.push("| Vertical | Repo | Design Innovation |");
    lines.push("|---|---|---|");
    for (const v of VERTICALS) {
      const cell = MATRIX[v.code]?.[s.code];
      if (cell) {
        lines.push(`| **${v.name}** | [\`${cell.repo}\`](https://github.com/mizcausevic-dev/${cell.repo}) | ${cell.innovation} |`);
      } else {
        lines.push(`| **${v.name}** | _not yet built_ | _N/A_ |`);
      }
    }
    lines.push("");
  }

  // --- Section 4: Cross-Cutting Invariants ---
  lines.push("## Cross-Cutting Invariants");
  lines.push("");
  lines.push("The same conceptual invariant appears in multiple verticals — but named, scoped, and enforced differently in each. This is where the parallel-structure thesis shows its richest texture.");
  lines.push("");
  for (const inv of CROSS_CUTTING_INVARIANTS) {
    lines.push(`### ${inv.concept}`);
    lines.push("");
    lines.push("| Vertical | Per-vertical naming / scope |");
    lines.push("|---|---|");
    for (const v of VERTICALS) {
      const n = inv.vertical_naming[v.code];
      lines.push(`| **${v.name}** | ${n || "_N/A_"} |`);
    }
    lines.push("");
  }

  // --- Section 5: How to Use This Table ---
  lines.push("## How to use this comparison");
  lines.push("");
  lines.push("**Buyer's procurement team**: Use the 6 × 6 matrix to understand which Suite shapes apply to your AI vendor portfolio across mixed regulated verticals. The same procurement Decision Card pattern works for a HealthTech AI vendor AND a FinTech AI vendor — the vault-contract data categories + consent_basis taxonomy differ, but the shape is identical.");
  lines.push("");
  lines.push("**Compliance counsel**: Use the cross-cutting invariants table to map equivalent obligations across regulated lines of business — when your firm advises clients across multiple verticals, the four-fifths-rule (PropTech, InsurTech, HR Tech, FinTech) and human-in-loop (HealthTech, PropTech, InsurTech, HR Tech, FinTech) patterns transfer with vertical-specific scoping rules.");
  lines.push("");
  lines.push("**AI vendor**: Use the per-shape matrix to identify the right Suite spec your product should target. If you're an AI vendor selling into FinTech, your Decision Card should conform to `financial-customer-data-vault-contract-v0.1`. If you sell into both InsurTech AND FinTech, you produce two Decision Cards using the same shape with the right vertical-specific profile.");
  lines.push("");
  lines.push("**Standards observer**: The matrix is a longitudinal record of how AI-governance design patterns transfer across regulated verticals — and where each vertical contributes a novel pattern (e.g. InsurTech's `actuarial-soundness-defended`, HR Tech's two-orthogonal-invariants audit stream, FinTech's institution-type-aware regulator routing).");
  lines.push("");

  // --- Section 6: Programmatic access ---
  lines.push("## Programmatic access");
  lines.push("");
  lines.push("```bash");
  lines.push("# Render this comparison fresh:");
  lines.push("npx kg-suite-vertical-comparator > CROSS-VERTICAL-COMPARISON.md");
  lines.push("");
  lines.push("# Or as JSON:");
  lines.push("npx kg-suite-vertical-comparator --json > comparison.json");
  lines.push("");
  lines.push("# Compare two specific artifacts:");
  lines.push("npx kg-suite-vertical-comparator --compare proptech-event.json fintech-event.json");
  lines.push("```");
  lines.push("");

  lines.push("## License");
  lines.push("");
  lines.push("This generated comparison is MIT-licensed. Reuse it on procurement comparison sheets, RFPs, internal training, vendor due-diligence packages — anywhere a buyer or seller needs the canonical \"same shape, different vertical\" reference.");
  lines.push("");

  return lines.join("\n");
}
